import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

import ClientProviders from "@/providers/ClientProvider";

export const metadata: Metadata = {
  title: "React Basic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <Navbar />
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
